### ISSUE TITLE
How about adding constructors like Either.left, Option.some?

### ISSUE THREAD

**Issue by jeiea** [cbyad/either_option#2]
Foreigners who doesn't know background of the names may try finding constructors from `Either` and `Option`.
`Either` and `Option` is closed class, and inseparable from the derived types. I think this is adoptable and can help beginners.

**Comment by cbyad** [comment]
While `Either` and `Option` is closed class you can't try finding constructors, It's a basic property of OOP. In this lib we use an `OOP` approach on `Either` and `Option`. I think if you are foreigner the first thing is to refer to the doc or read examples, is the same practice to proceed with a new lib, framework or anything else.
 So to get an Option instance, you  have many choices: constructors `Some(foobar)` and `None()` or static method `Option.of(foobar) 
` and `Option.empty`,  in this case a Option.some is unnecessary.
To get an Either instance, you have Left(foobar) and Right(foobar), in this case even if I think is unnecessary, yes we can add a `Either.left` or `Either.right`

**Comment by jeiea** [comment]
Well, it's just a suggestion and have a risk of increasing API surface, it may be rejected.

Just for curiosity, may I ask a more clarification?
> While `Either` and `Option` is closed class you can't try finding constructors, It's a basic property of OOP.

I don't want to use reflection to find constructor, but I thought someone can use autocompletion to find a way to construct a instance of `Either`. At now it's not easy to find `Either` implementors from autocompletion information.

I can't sure what did you exactly mean by *basic property of OOP*. What I can think of is polymorphism (by inheritance, etc..) can break a link between abstract and concrete code, and make it difficult to track concrete code. Strictly speaking we can't easily search constuctors excluding default or named constructor as you say, but I thought it's slightly different from discoverability of methods. So did you mean something other than this?

**Comment by cbyad** [comment]
I understand your view. But I don't think that we build a library base on helping by auto-completion in first. Sorry I meant abstract instead of closed to say due this fact we can't think of finding constructors on them even if you don't talk about reflection.
you can open a PR to add a static method `Either.left` and` Either.right `if you think is a good think. But for Option we have Option.of to create a Some instance otherwise a None if content is null

**Comment by cbyad** [comment]
@jeiea what about the PR?

**Comment by jeiea** [comment]
I don't have a plan now.
