### ISSUE TITLE
NNBD support

### ISSUE THREAD

**Issue by jeiea** [cbyad/either_option#3]
It seems the package does not support NNBD and has no branch for it. Can I make a PR?

**Comment by cbyad** [comment]
Yes you can. I was wondering if It's valuable to used it because functional type like Option are by def guard against null value. But yes you can make a PR

**Comment by jeiea** [comment]
> We strongly recommend migrating code in order, with the leaves of the dependency graph being migrated first. For example, if package C depends on package B, which depends on package A, then A should be migrated to null safety first, then B, then C.

So if we don't migrate this package, applications which depends on this package can't be migrated neither.

**Comment by cbyad** [comment]
Great. This package depends only on test lib which have already be migrated to NNDB so yes you can make a PR for that right now 🤓
