### ISSUE TITLE
Addition of getOrNull

### ISSUE THREAD

**Issue by jeiea** [cbyad/either_option#6]
One of the breaking changes of adopting null safety is the following.

```
final n = Some(3);
// pass
n.fold(() => null, (x) => x);
// can't pass
n.getOrElse(null);
```

Current `getOrElse` implementation is this.
```
A getOrElse(A caseElse) => fold(() => caseElse, (A a) => a);
```

I couldn't find the signature accepting `n.getOrElse(null)`. It can be bypassed by using `fold` directly so it doesn't require an immediate action, but it can be a consideration point.

**Comment by cbyad** [comment]
Hi @jeiea sorry for the late reply.
Yes It can be a consideration point. 
One solution to solve this is to change `getOrElse` implemetation like this

```dart
A? getOrElse(A? caseElse) => fold(() => caseElse, (A a) => a);
```
Second point is value passed to `getOrElse` should be lazy (not computed directly). So by adding lazy and mixing null-safety support. we will get this

```dart
A? getOrElse(A? Function() caseElse) => fold(caseElse, (A a) => a);
```
I will make an upgrade of the lib to apply this
